[phases.setup]
nixPkgs = ["nodejs-18_x", "postgresql"]

[phases.install]
cmds = ["npm run install:all"]

[phases.build]
cmds = ["cd server && npx prisma generate", "npm run build"]

[start]
cmd = "cd server && npx prisma migrate deploy && cd .. && npm start" 