[phases.setup]
nixPkgs = ["nodejs-18_x", "npm-9_x"]

[phases.install]
cmds = ["cd server && npm install", "cd ../client && npm install"]

[phases.build]
cmds = ["cd server && npm run build && npx prisma generate", "cd ../client && npm run build"]

[start]
cmd = "cd server && npx prisma migrate deploy && npm start" 